update
yangzf-1023/Interactive-Clock pull request #4
Opened 2024-07-23 10:59 UTC by Altocumuli

实现了闹钟功能

2024-07-23 16:30 UTC, gtxzsxxk requested changes

2024-07-23 16:30 UTC, gtxzsxxk commented on index.html
> +        <!-- 主要内容区域 -->
你这里不应该是`container` -> `row` -> `col-md-10`的关系，因为你的col-md-10里边的元素还有`row`和`col`这几个元素，根据我已有的可能过时的知识，这样的布局可能不是正确的，你应该建立如下布局：

```
container
    row
        col col ....
    row
        col col ....
    row
        col col ....
```

2024-07-23 16:30 UTC, gtxzsxxk commented on index.html
> +            <div class="row justify-content-center mt-5">
请你保证文本框和按钮的尺寸与上一行的时分秒和按钮这些元素都是一致的，建议你不要把闹钟功能放在时分秒设置的下一行，而是把它放到你的侧边栏那里

2024-07-23 16:30 UTC, gtxzsxxk commented on scripts/script.js
> +cancelAlarmButton.addEventListener('click', function () {
闹钟有bug，响了之后点击已开启、已关闭、或者叉后不能把声音停掉

2024-07-23 16:30 UTC, gtxzsxxk commented on scripts/script.js
> +    const now = new Date();
闹钟响的时间，应该是这个时钟表盘的时间，不是我的系统时间！

2024-07-23 16:30 UTC, gtxzsxxk commented on styles/style.css
> +
可以改宽一点，元素之间margin调大一些

2024-07-24 03:55 UTC, Altocumuli commented on scripts/script.js
> +cancelAlarmButton.addEventListener('click', function () {
我是仿照iPhone闹钟功能，“已开启”、“已关闭”按钮是用于设置闹钟的可重复性，“叉”是用于清除闹钟项，响后点击“停止闹钟”即可关闭它

2024-07-24 03:57 UTC, gtxzsxxk commented on scripts/script.js
> +cancelAlarmButton.addEventListener('click', function () {
> 我是仿照iPhone闹钟功能，“已开启”、“已关闭”按钮是用于设置闹钟的可重复性，“叉”是用于清除闹钟项，响后点击“停止闹钟”即可关闭它

停止闹钟这个按钮是在设置时间那一行的下面一行吗？我的页面高度不够，设置时间下边的一行要滚动鼠标才能看到

2024-07-24 04:00 UTC, Altocumuli commented on scripts/script.js
> +cancelAlarmButton.addEventListener('click', function () {
嗯嗯是的，我一会调调布局

2024-07-25 10:01 UTC, gtxzsxxk approved these changes
LGTM

2024-07-25 10:01 UTC, merged